FROM drupal:7.54-apache
MAINTAINER Maintained by IT Trailblazers
ENV MYSQL_ROOT_PASSWORD some_password
ENV MYSQL_DATABASE drupal
ENV MYSQL_USER drupal
ENV MYSQL_PASSWORD drupal
ENV MYSQL_HOST 172.17.0.2
ENV DRUSH_VERSION 7.3.0
ENV MYSQL_MAJOR 5.72
ENV MYSQL_VERSION 5.7.17-1debian8
EXPOSE 80 22 
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php && php -r "unlink('composer-setup.php');"
RUN cp composer.phar /usr/local/bin/composer && composer global require drush/drush:"$DRUSH_VERSION" --prefer-dist
RUN set -ex; \
# gpg: key 5072E1F5: public key "MySQL Release Engineering <mysql-build@oss.oracle.com>" imported
key='A4A9406876FCBD3C456770C88C718D3B5072E1F5'; \
export GNUPGHOME="$(mktemp -d)"; \
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
gpg --export "$key" > /etc/apt/trusted.gpg.d/mysql.gpg; \
rm -r "$GNUPGHOME"; \
apt-key list > /dev/null
#RUN echo "deb http://repo.mysql.com/apt/debian/ jessie mysql-${MYSQL_MAJOR}" > /etc/apt/sources.list.d/mysql.list
#RUN apt-get update && apt-get install -y git mysql-community-client
RUN apt-get update && apt-get install -y git
#RUN mysql -u root --password=$MYSQL_ROOT_PASSWORD --host=$MYSQL_HOST -e "drop database drupal; CREATE DATABASE drupal; GRANT ALL ON drupal.* TO 'drupal'@'%';"
# Uncomment this out if you want to go traditional way of setting up Drupal
#RUN /root/.composer/vendor/bin/drush si standard -y --db-url=mysql://drupal:drupal@172.17.0.2/drupal
#ADD settings.php.default /tmp
#ADD runcode.sh /tmp 
#ADD docker-php-entrypoint /usr/local/bin
#RUN /tmp/runcode.sh 
CMD ["docker-php-entrypoint", "/usr/sbin/apache2ctl","-D FOREGROUND"]
