FROM mysql:latest
MAINTAINER Maintained by IT Trailblazers
ENV MYSQL_ROOT_PASSWORD some_password
ENV MYSQL_DATABASE drupal
ENV MYSQL_USER drupal
ENV MYSQL_PASSWORD drupal
RUN apt-get update && apt-get install -y git && ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime 
#COPY ./my.cnf /etc/alternatives/my.cnf
#COPY ./my.cnf /etc/mysql/conf.d
RUN chown -R mysql:mysql /var/lib/mysql
RUN echo "default-character-set=utf8" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_set_client utf8" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_set_connection utf8" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_set_database utf8" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_set_filesystem binary" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_set_results utf8" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_set_server utf8" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_set_system utf8" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "character_sets_dir /usr/share/mysql/charsets/" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "collation_connection utf8_general_ci" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "collation_database utf8_general_ci" >> /etc/mysql/conf.d/mysql.cnf
RUN echo "collation_server utf8_general_ci" >> /etc/mysql/conf.d/mysql.cnf
CMD ["mysqld"]
