FROM eeacms/varnish:latest
MAINTAINER Maintained by IT Trailblazers
#ENV ADDRESS_PORT 6081 
#ENV ADMIN_PORT 6082 
#ENV DNS_ENABLED false 
#ENV BACKENDS ec2-52-77-233-238.ap-southeast-1.compute.amazonaws.com:8000
EXPOSE 6081
COPY default.vcl /etc/varnish/default.vcl
